services:
  - type: web
    name: mlb-stats-explorer
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: shiny run app.py --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9 